#pragma once

#include "CoreMinimal.h"
#include "ForgeQABuildContext.h"

/**
 * The current, versioned schema of the ForgeQA build manifest file. Bump this whenever the JSON
 * shape changes in a way older readers cannot tolerate, and keep TryParseJsonString able to
 * reject (rather than misinterpret) manifests from a newer, incompatible schema.
 */
constexpr int32 ForgeQABuildManifestSchemaVersion = 1;

/**
 * In-memory representation of the ForgeQA build manifest: the packaged, offline-readable record
 * of which ForgeQA Project and Build a compiled game belongs to. Generated by the Editor
 * integration (see FForgeQAEditorModule) from verified Build Registry data; read-only at runtime.
 */
struct FORGEQA_API FForgeQABuildManifest
{
    int32 SchemaVersion = ForgeQABuildManifestSchemaVersion;

    FGuid ProjectId;
    FGuid BuildId;

    FString Version;
    FString BuildNumber;
    FString Platform;
    FString Configuration;
    FString Branch;
    FString CommitSha;

    bool IsValid() const
    {
        return ProjectId.IsValid() && BuildId.IsValid();
    }

    FForgeQABuildContext ToBuildContext() const;
};

/** Reads/writes FForgeQABuildManifest as the JSON document described in docs/unreal-integration.md. */
class FORGEQA_API FForgeQABuildManifestSerializer
{
public:
    /** Deterministic packaged-content location: <ProjectContentDir>/ForgeQA/ForgeQABuild.json. */
    static FString GetManifestFilePath();

    static FString ToJsonString(const FForgeQABuildManifest& Manifest);

    /** Never throws; returns false and fills OutError on malformed JSON, a missing field, an
     *  invalid UUID, or an unsupported (newer) schema version. */
    static bool TryParseJsonString(const FString& JsonString, FForgeQABuildManifest& OutManifest, FString& OutError);

    static bool TryLoadFromFile(FForgeQABuildManifest& OutManifest, FString& OutError);
    static bool TryLoadFromFile(const FString& FilePath, FForgeQABuildManifest& OutManifest, FString& OutError);

    static bool SaveToFile(const FForgeQABuildManifest& Manifest, FString& OutError);
};
